#deployment details for (book_catalog)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book_catalog
  labels:
    app: book_catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book_catalog
  template:
    metadata:
      labels:
        app: book_catalog
    spec:
      containers:
      - name: book_catalog_cnt
        image: $CONTAINER_REGISTRY.azurecr.io/book_catlog_az:$VERSION
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "4001"
        - name: DATABASE_URL
          value: postgresql://manish_project_part5_user:ZXl9CUIEqzWlZW1b78kMIag141IUtevb@dpg-crl5n5jtq21c73e8dh0g-a.oregon-postgres.render.com/manish_project_part5
---
apiVersion: v1
kind: Service
metadata:
  name: book_catalog
spec:
  selector:
    app: book_catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 31001
      targetPort: 4001


---

#deployment details for (inventory_management)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory_management
  labels:
    app: inventory_management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory_management
  template:
    metadata:
      labels:
        app: inventory_management
    spec:
      containers:
      - name: inventory_management_cnt
        image: $CONTAINER_REGISTRY.azurecr.io/inventory_management_az:$VERSION
        imagePullPolicy: IfNotPresent 
        env:
        - name: PORT
          value: "5001"
        - name: DATABASE_URL
          value: postgresql://manish_project_part5_user:ZXl9CUIEqzWlZW1b78kMIag141IUtevb@dpg-crl5n5jtq21c73e8dh0g-a.oregon-postgres.render.com/manish_project_part5
---
apiVersion: v1
kind: Service
metadata:
  name: inventory_management
spec:
  selector:
    app: inventory_management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 32001
      targetPort: 5001